import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import {BsSearch} from "react-icons/bs";

export default function Home(){
  
  /*Creating a state for the city to be searched for and setting it as an empty string, user has to input this. Weather state is set as an empty object*/
  const [city, setCity] = useState('');
  const [weahter,setWeather] = useState({});
  const [loading,setLoading] = useState(false);

  const apikey = process.env.NEXT_PUBLIC_WEATHER_KEY

  const url = "https://api.openweathermap.org/data/2.5/weather?q=doha&appid=0daee2d4682e59fab04560bc2b44954f";


  /*To stop the api to run whenever the page loads*/
  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true)
    axios.get(url).then((response) => {
      setWeather(response.data)
      console.log(response.data)
    })
    setCity('')
    setLoading(false)
  }

  

  return(
    <div>
      <Head>
        <title>Weather - Next app</title>
        <meta name="description" content="generated by whoever"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <h1 className="text-3xl text-white">Hello</h1>

      <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/50 z-[1]"/>

      <Image className="object-cover z-0" src="https://www.pixelstalk.net/wp-content/uploads/2016/07/Free-Download-Weather-Background.jpg" fill="overlay" ></Image>

      {/*search */}

      <div className="relative flex justify-between items-center max-w-[500px] w-full margin-auto pt-4 text-white z-10">
        <form className="flex justify-between items-center w-full m-auto p-3 bg-transparent border-gray-300 text-white rounded-2xl">
          <div>
            <input type="text" placeholder="Search city" />
          </div>
          <button onClick={fetchWeather}><BsSearch/></button>
        </form>
      </div>

    </div>
  )
}