import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import {BsSearch} from "react-icons/bs";
import Weather  from "../component/Weather";
import Loader from "../component/Loader";

export default function Home(){
  
  /*Creating a state for the city to be searched for and setting it as an empty string, user has to input this. Weather state is set as an empty object*/
  const [city, setCity] = useState('');
  const [weather,setWeather] = useState({});
  const [loading,setLoading] = useState(false);

  const apikey = process.env.NEXT_PUBLIC_WEATHER_KEY

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;


  /*To stop the api run everytime the page loads*/
  const fetchWeather = (event) => {
    event.preventDefault()
    setLoading(true)
    axios.get(url).then((response) => {
      setWeather(response.data);
      // console.log(response.data);
    })
    setCity('')
    setLoading(false)
  }

  if(loading) {
    return <Loader />;
  } else {

  return(
    <div>
      <Head>
        <title>Weather - Next app</title>
        <meta name="description" content="generated by whoever"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <br/>


    
      {/*search */}
      <div className="relative flex justify-center items-center max-w-[500px] px-4 m-auto pt-4 text-white z-10">
        
        <form 
        onSubmit={fetchWeather}
        className="flex justify-between items-center w-full m-auto p-3 bg-transparent text-white border-white border-2 rounded-2xl">
          <div>


            <input 
            onChange={(event)=> setCity(event.target.value)} 
            className="min-w-full bg-transparent border-none text-white focus:outline-none text-2xl placeholder:text-white " 
            type="text" 
            placeholder="Search city" />


          </div>
          <button  onClick={fetchWeather}><BsSearch size={20}/></button>
        </form>
        
      </div>
 {/* Weather */}
      
 <div className="flex flex-col"> 
      {weather.main && <Weather data={weather} />}
      </div>


      <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/50 -z-10"/>
      <Image className="object-cover -z-20" src="https://images8.alphacoders.com/543/543152.jpg" fill="overlay" alt="beautiful background of hills clouds and trees"/>
      
     

    </div>
    
  );
}

  }
  

  